engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - "**.rb"
  - "**.js"
exclude_paths:
- "vendor/**/*"
- "db/schema.rb"
- "Gemfile"
- "config/**/*"
- "spec/rails_helper.rb"
- "spec/spec_helper.rb"
